{
    "Barack Obama": "Former President of the United States, known for the Affordable Care Act",
    "Michelle Obama": "Former First Lady, author of 'Becoming', advocate for healthy eating",
    "Barack H. Obama": "44th President of the USA, Nobel Peace Prize winner",
    "B. Obama": "Ex-U.S. President, first African-American president",
    "Elon Musk": "CEO of Tesla and SpaceX, known for pushing AI and space exploration",
    "E. Musk": "Founder of SpaceX, advocate for interplanetary travel, CEO of Tesla",
    "Jeff Bezos": "Founder of Amazon, space entrepreneur",
    "J. Bezos": "Blue Origin founder, billionaire investor",
    "Jeffrey Bezos": "E-commerce pioneer, owner of The Washington Post",
    "Bill Gates": "Co-founder of Microsoft, philanthropist",
    "William Gates": "Tech mogul, founded the Bill & Melinda Gates Foundation",
    "B. Gates": "Billionaire investor, software pioneer, Microsoft co-founder",
    "Steve Jobs": "Apple co-founder, known for revolutionizing smartphones",
    "Steven P. Jobs": "Visionary entrepreneur, led Apple’s innovation",
    "Tim Cook": "Current CEO of Apple, advocate for privacy and sustainability",
    "T. Cook": "Apple leader, successor to Steve Jobs",
    "Warren Buffett": "Investor, CEO of Berkshire Hathaway, known for value investing",
    "W. Buffett": "Financial guru, longtime leader at Berkshire Hathaway",
    "Sergey Brin": "Google co-founder, AI researcher",
    "Larry Page": "Google co-founder, Alphabet executive",
    "L. Page": "Search engine innovator, AI-focused entrepreneur",
    "Bernie Sanders": "U.S. Senator, advocate for progressive policies",
    "Bernard Sanders": "Politician known for advocating Medicare for All",
    "Joe Biden": "46th President of the United States",
    "J. Biden": "Current U.S. President, formerly Vice President under Obama",
    "Jordan Peterson": "Psychologist, known for self-help books and cultural commentary",
    "Jordan B. Peterson": "Canadian professor, author of '12 Rules for Life'",
    "Peter Jordanson": "Influential speaker on self-improvement and social issues",
    "Richard Branson": "Founder of Virgin Group, billionaire entrepreneur",
    "Dick Branson": "Business magnate, known for Virgin Airlines",
    "Rick Branson": "Investor and adventurer, linked to the Virgin brand"
}


You are an AI that processes a dictionary of entity names and descriptions to group 
similar entities based on name variations and description similarities. Your goal is to:
1. Iterate over each entity in the dictionary using a for loop.
2. Compare its description with every other entity’s description.
3. Group entities that refer to the same person while keeping distinct entities separate, even if they have similar descriptions.
4. Return the output as a JSON object where each key is a unique entity and the value is a list of grouped names.




{
    "match1": ["Barack Obama", "Barack H. Obama"],
    "match2": ["Barack Obama", "B. Obama"],
    "match3": ["Barack Obama", "Elon Musk"],
    "match4": ["Barack Obama", "E. Musk"],
    "match5": ["Barack Obama", "Jeff Bezos"],
    "match6": ["Barack Obama", "J. Bezos"],
    "match7": ["Barack Obama", "Jeffrey Bezos"],
    "match8": ["Barack Obama", "Bill Gates"],
    "match9": ["Barack Obama", "William Gates"],
    "match10": ["Barack Obama", "B. Gates"],
    "match11": ["Barack Obama", "Steve Jobs"],
    "match12": ["Barack Obama", "Steven P. Jobs"],
    "match13": ["Barack Obama", "Tim Cook"],
    "match14": ["Barack Obama", "T. Cook"],
    "match15": ["Barack Obama", "Warren Buffett"],
    "match16": ["Barack Obama", "W. Buffett"],
    "match17": ["Barack Obama", "Sergey Brin"],
    "match18": ["Barack Obama", "Larry Page"],
    "match19": ["Barack Obama", "L. Page"],
    "match20": ["Barack Obama", "Bernie Sanders"],
    "match21": ["Barack Obama", "Bernard Sanders"],
    "match22": ["Barack Obama", "Joe Biden"],
    "match23": ["Barack Obama", "J. Biden"],
    "match24": ["Barack Obama", "Jordan Peterson"],
    "match25": ["Barack Obama", "Jordan B. Peterson"],
    "match26": ["Barack Obama", "Peter Jordanson"],
    "match27": ["Barack Obama", "Richard Branson"],
    "match28": ["Barack Obama", "Dick Branson"],
    "match29": ["Barack Obama", "Rick Branson"],
    "match30": ["Barack H. Obama", "B. Obama"],
    "match31": ["Barack H. Obama", "Elon Musk"],
    "match32": ["Barack H. Obama", "E. Musk"],
    "match33": ["Barack H. Obama", "Jeff Bezos"],
    "match34": ["Barack H. Obama", "J. Bezos"],
    "match35": ["Barack H. Obama", "Jeffrey Bezos"],
    "match36": ["Barack H. Obama", "Bill Gates"],
    "match37": ["Barack H. Obama", "William Gates"],
    "match38": ["Barack H. Obama", "B. Gates"],
    "match39": ["Barack H. Obama", "Steve Jobs"],
    "match40": ["Barack H. Obama", "Steven P. Jobs"],
    "match41": ["Barack H. Obama", "Tim Cook"],
    "match42": ["Barack H. Obama", "T. Cook"],
    "match43": ["Barack H. Obama", "Warren Buffett"],
    "match44": ["Barack H. Obama", "W. Buffett"],
    "match45": ["Barack H. Obama", "Sergey Brin"],
    "match46": ["Barack H. Obama", "Larry Page"],
    "match47": ["Barack H. Obama", "L. Page"],
    "match48": ["Barack H. Obama", "Bernie Sanders"],
    "match49": ["Barack H. Obama", "Bernard Sanders"],
    "match50": ["Barack H. Obama", "Joe Biden"],
    "match51": ["Barack H. Obama", "J. Biden"],
    "match52": ["Barack H. Obama", "Jordan Peterson"],
    "match53": ["Barack H. Obama", "Jordan B. Peterson"],
    "match54": ["Barack H. Obama", "Peter Jordanson"],
    "match55": ["Barack H. Obama", "Richard Branson"],
    "match56": ["Barack H. Obama", "Dick Branson"],
    "match57": ["Barack H. Obama", "Rick Branson"],
    "match58": ["B. Obama", "Elon Musk"],
    "match59": ["B. Obama", "E. Musk"],
    "match60": ["B. Obama", "Jeff Bezos"],
    "match61": ["B. Obama", "J. Bezos"],
    "match62": ["B. Obama", "Jeffrey Bezos"],
    "match63": ["B. Obama", "Bill Gates"],
    "match64": ["B. Obama", "William Gates"],
    "match65": ["B. Obama", "B. Gates"],
    "match66": ["B. Obama", "Steve Jobs"],
    "match67": ["B. Obama", "Steven P. Jobs"],
    "match68": ["B. Obama", "Tim Cook"],
    "match69": ["B. Obama", "T. Cook"],
    "match70": ["B. Obama", "Warren Buffett"],
    "match71": ["B. Obama", "W. Buffett"],
    "match72": ["B. Obama", "Sergey Brin"],
    "match73": ["B. Obama", "Larry Page"],
    "match74": ["B. Obama", "L. Page"],
    "match75": ["B. Obama", "Bernie Sanders"],
    "match76": ["B. Obama", "Bernard Sanders"],
    "match77": ["B. Obama", "Joe Biden"],
    "match78": ["B. Obama", "J. Biden"],
    "match79": ["B. Obama", "Jordan Peterson"],
    "match80": ["B. Obama", "Jordan B. Peterson"],
    "match81": ["B. Obama", "Peter Jordanson"],
    "match82": ["B. Obama", "Richard Branson"],
    "match83": ["B. Obama", "Dick Branson"],
    "match84": ["B. Obama", "Rick Branson"]
}
